export const SET_TITLE = 'SET_TITLE';
export const INCREMENT_COUNT = 'INCREMENT_COUNT';
export const INCREMENT_COUNT_START = 'INCREMENT_COUNT_START';
export const INCREMENT_COUNT_FAIL = 'INCREMENT_COUNT_FAIL';
export const DECREMENT_COUNT = 'DECREMENT_COUNT';
export const DECREMENT_COUNT_START = 'DECREMENT_COUNT_START';
export const DECREMENT_COUNT_FAIL = 'DECREMENT_COUNT_FAIL';

export const FETCH_USER_START = 'FETCH_USER_START';
export const AUTH_CHECK_STATE_START = '.AUTH_CHECK_STATE_START';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';

export const USER_FETCH_SUCCEEDED = 'USER_FETCH_SUCCEEDED';
